import groovy.json.JsonSlurper

def productConfig = new JsonSlurper().parse(file("config/product.json"))

buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    ext {
        minSdkVersion = productConfig.android.minSdk
        targetSdkVersion = productConfig.android.targetSdk
        compileSdkVersion = productConfig.android.compileSdk
        ndkVersion = productConfig.android.ndkVersion
    }

    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
